### ISSUE TITLE
Unit tests do work on Windows ... not on Linux

### ISSUE THREAD

**Issue by macsnoeren** [macsnoeren/python-p2p-network#8]
The unit tests that are created to test all the functionality of the package do work on Windows. On Linux it fails unfortunately. This should be investigated and solved. The following output is shown when the tests are runned on Linux:
```
$ python3 setup.py test
running test
Searching for nose
Best match: nose 1.3.7
Processing nose-1.3.7-py3.7.egg

Using /home/maurice/projects/python-p2p-network/.eggs/nose-1.3.7-py3.7.egg
running egg_info
writing p2pnetwork.egg-info/PKG-INFO
writing dependency_links to p2pnetwork.egg-info/dependency_links.txt
writing top-level names to p2pnetwork.egg-info/top_level.txt
reading manifest file 'p2pnetwork.egg-info/SOURCES.txt'
writing manifest file 'p2pnetwork.egg-info/SOURCES.txt'
running build_ext
test_extending_class_of_node (p2pnetwork.tests.test_node.TestNode)
Testing the class implementation of the Node. ... ok
test_node_communication (p2pnetwork.tests.test_node.TestNode)
Test whether the connected nodes are able to send messages to each other. ... ok
test_node_complete (p2pnetwork.tests.test_node.TestNode)
Testing the complete sequence of the Node based on Samuel complete_test.py. ... ERROR
/usr/lib/python3.7/unittest/case.py:643: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  outcome.errors.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
test_node_connection (p2pnetwork.tests.test_node.TestNode)
Testing whether two Node instances are able to connect with each other. ... ERROR
/usr/lib/python3.7/unittest/case.py:643: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  outcome.errors.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/unittest/case.py:643: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 10001)>
  outcome.errors.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
test_node_events (p2pnetwork.tests.test_node.TestNode)
Testing the events that are triggered by the Node. ... ERROR
test_node_send_data_dict (p2pnetwork.tests.test_nodeconnection.TestNode)
Testing whether NodeConnections handle sending dict well enough. ... ERROR
/usr/lib/python3.7/unittest/case.py:643: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8001)>
  outcome.errors.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
test_node_send_data_str (p2pnetwork.tests.test_nodeconnection.TestNode)
Testing whether NodeConnections handle sending str well enough. ... ERROR

======================================================================
ERROR: test_node_complete (p2pnetwork.tests.test_node.TestNode)
Testing the complete sequence of the Node based on Samuel complete_test.py.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/tests/test_node.py", line 121, in test_node_complete
    node_0 = Node('127.0.0.1', 8000, node_callback)
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/node.py", line 69, in __init__
    self.init_server()
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/node.py", line 92, in init_server
    self.sock.bind((self.host, self.port))
OSError: [Errno 98] Address already in use
-------------------- >> begin captured stdout << ---------------------
Initialisation of the Node on port: 8000 on node (ed8bab37d7f15e30da8720e96bcad500f2f8025ff06cbee97eb82bba8498baa444b3937d6bcae3945622421f38a27739cbfa91a3a6a22380caba42d7fff3b79d)

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_node_connection (p2pnetwork.tests.test_node.TestNode)
Testing whether two Node instances are able to connect with each other.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/tests/test_node.py", line 21, in test_node_connection
    node2 = Node("localhost", 10002)
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/node.py", line 69, in __init__
    self.init_server()
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/node.py", line 92, in init_server
    self.sock.bind((self.host, self.port))
OSError: [Errno 98] Address already in use
-------------------- >> begin captured stdout << ---------------------
Initialisation of the Node on port: 10001 on node (da332f1ea0d8ef643c9fae02837ee76911d8d4bb0c9edc3ac12ffb7078c69a46cdc1cc61dc2b1f9aa4abe86720dd959a5af6ceb383812bef0c58281c62cc7c90)
Initialisation of the Node on port: 10002 on node (0c265613937e77eb17a9039f3d4c7ac9b11a6b591b5e12077241f197f92f56eabeb23c3ce0b0c925154a3085ef76c0528b8897ddfb115ce3915e574c12923db9)

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_node_events (p2pnetwork.tests.test_node.TestNode)
Testing the events that are triggered by the Node.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/tests/test_node.py", line 207, in test_node_events
    node_0 = Node('127.0.0.1', 8000, node_callback)
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/node.py", line 69, in __init__
    self.init_server()
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/node.py", line 92, in init_server
    self.sock.bind((self.host, self.port))
OSError: [Errno 98] Address already in use
-------------------- >> begin captured stdout << ---------------------
Initialisation of the Node on port: 8000 on node (bcd13e8d7236a4bdb27a1edd3f0d188b1f0122f80891f6977922ff5ce51618e3a8a05f5b47a715b632e58a80185cff967e2a582f4ddef9dabf32ebfc6cefae36)

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_node_send_data_dict (p2pnetwork.tests.test_nodeconnection.TestNode)
Testing whether NodeConnections handle sending dict well enough.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/tests/test_nodeconnection.py", line 100, in test_node_send_data_dict
    node2 = MyTestNode("127.0.0.1", 8002)
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/tests/test_nodeconnection.py", line 88, in __init__
    super(MyTestNode, self).__init__(host, port, None)
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/node.py", line 69, in __init__
    self.init_server()
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/node.py", line 92, in init_server
    self.sock.bind((self.host, self.port))
OSError: [Errno 98] Address already in use
-------------------- >> begin captured stdout << ---------------------
Initialisation of the Node on port: 8001 on node (2fe5423ad2fa43b023063a3a54f3fb6e28768c574ecf14de8621135195d87591327191cdf905d03a05e70c7021e9fe658ae30188cd08939dc201ee029239c6fd)
Initialisation of the Node on port: 8002 on node (aa90124307d53a8e8ed99bbd8d624c1adc5668a78830c58238480fac76762c2be37d55992637c04cd7ae5800f9235777f053a55d365d06a3e7feb2513b236b93)

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_node_send_data_str (p2pnetwork.tests.test_nodeconnection.TestNode)
Testing whether NodeConnections handle sending str well enough.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/tests/test_nodeconnection.py", line 36, in test_node_send_data_str
    node2 = MyTestNode("127.0.0.1", 8002)
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/tests/test_nodeconnection.py", line 26, in __init__
    super(MyTestNode, self).__init__(host, port, None)
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/node.py", line 69, in __init__
    self.init_server()
  File "/home/maurice/projects/python-p2p-network/p2pnetwork/node.py", line 92, in init_server
    self.sock.bind((self.host, self.port))
OSError: [Errno 98] Address already in use
-------------------- >> begin captured stdout << ---------------------
Initialisation of the Node on port: 8001 on node (371fae118c3037f1a2f2cdec60f1f2729a0da7b2b6433f639f43dca722ecd5c928bdb4d1b5de66d5c82b8322d2fc6300caa974ded873e13a1eb7238e98d67ab7)
Initialisation of the Node on port: 8002 on node (752f24de3d4dfaf4ec126ada2f13c278c7992a383cd21b248600df0daac3ea07c7c685810166766ac4b6348b2946ae9d79d2a0dacd324cfdded5d806ca877008)

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 7 tests in 28.110s

FAILED (errors=5)
Test failed: <unittest.runner.TextTestResult run=7 errors=5 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=7 errors=5 failures=0>
```

**Comment by macsnoeren** [comment]
The issue has been solved by changing the class Node to reuse the port. Furthermore, the port 800x has been changed to 1000x. See the comments in the repo for more information. The following output was generated on a Unix machine running Debian:

````
$ python setup.py test
running test
Searching for nose
Best match: nose 1.3.7
Processing nose-1.3.7-py3.7.egg

Using /home/maurice/projects/python-p2p-network/.eggs/nose-1.3.7-py3.7.egg
running egg_info
writing p2pnetwork.egg-info/PKG-INFO
writing dependency_links to p2pnetwork.egg-info/dependency_links.txt
writing top-level names to p2pnetwork.egg-info/top_level.txt
reading manifest file 'p2pnetwork.egg-info/SOURCES.txt'
writing manifest file 'p2pnetwork.egg-info/SOURCES.txt'
running build_ext
test_extending_class_of_node (p2pnetwork.tests.test_node.TestNode)
Testing the class implementation of the Node. ... ok
test_node_communication (p2pnetwork.tests.test_node.TestNode)
Test whether the connected nodes are able to send messages to each other. ... ok
test_node_complete (p2pnetwork.tests.test_node.TestNode)
Testing the complete sequence of the Node based on Samuel complete_test.py. ... ok
test_node_connection (p2pnetwork.tests.test_node.TestNode)
Testing whether two Node instances are able to connect with each other. ... ok
test_node_events (p2pnetwork.tests.test_node.TestNode)
Testing the events that are triggered by the Node. ... ok
test_node_send_data_dict (p2pnetwork.tests.test_nodeconnection.TestNode)
Testing whether NodeConnections handle sending dict well enough. ... ok
test_node_send_data_str (p2pnetwork.tests.test_nodeconnection.TestNode)
Testing whether NodeConnections handle sending str well enough. ... ok

----------------------------------------------------------------------
Ran 7 tests in 138.308s

OK
````
